### ISSUE TITLE
Install Spacer on Fedora

### ISSUE THREAD

**Issue by amilenovic** [poga/spacer#3]
Spacer looks very interesting, so I wanted to try it on my Fedora 27 VM.

I followed instructions and installed `OpenResty` and `librdkafka` (and `librdkafka-devel`) sing `dnf install`. 

Then I tried `go get -u github.com/poga/spacer` as instructed. However, I got following error:

```# github.com/poga/spacer
/tmp/go-build061222208/libkafka.a263678367(event.cgo2.o): In function `_cgo_8faa275e9b44_Cfunc_rd_kafka_event_stats':
/home/amilenovic/go/src/github.com/poga/spacer/vendor/github.com/confluentinc/confluent-kafka-go/kafka/cgo-gcc-prolog:68: undefined reference to `rd_kafka_event_stats'
collect2: error: ld returned 1 exit status
```
Can you advise how to install Spacer on Fedora? Or even better, if there is a docker image container available that I can use?

Thanks

**Comment by poga** [comment]
Spacer requires a recent version of `librdkafka` (I've only tested on 0.11.4.)
You might want to check the version of `librdkafka` you've installed.

You can also try the [Dockerfile](https://github.com/poga/spacer/blob/master/Dockerfile) provided in the repo. It should be much easier.

**Comment by poga** [comment]
I'm closing this for now. Feel free to open it again if you need any help.
